package NewLanguage.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditorComponent;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new ActCommandHandler_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new AggregateRoot_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new Command_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new CommandHandler_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }

  @NotNull
  public Collection<ConceptEditorComponent> getDeclaredEditorComponents(SAbstractConcept concept, String editorComponentId) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        if (true) {
          if ("NewLanguage.editor.CommandHandlerComponent".equals(editorComponentId)) {
            return Collections.<ConceptEditorComponent>singletonList(new CommandHandlerComponent());
          }
        }
        break;
      default:
    }
    return Collections.<ConceptEditorComponent>emptyList();
  }

  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new ActCommandHandler_SubstituteMenu());
      case 1:
        return Collections.<SubstituteMenu>singletonList(new Command_SubstituteMenu());
      case 2:
        return Collections.<SubstituteMenu>singletonList(new CommandHandler_SubstituteMenu());
      case 3:
        return Collections.<SubstituteMenu>singletonList(new CreateCommandHandler_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb390ac2L), MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb34348bL), MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb310f74L), MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb310f73L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb310f73L)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb390ac2L), MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb310f74L), MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb310f73L), MetaIdFactory.conceptId(0x5bea80f0c6164ce6L, 0x8ffcdaee517fa801L, 0x49d1e6edfb38c9b9L)).seal();
}
